name: ml-fullstack
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas
  - scipy
  - jupyterlab
  - scikit-learn
  - matplotlib
  - pytest
  - seaborn
  - mlflow
  - numpy
prefix: /home/beinganujchaudhary/miniconda3/envs/ml-fullstack
